# ===== import 區域 =====
from flask import Flask, request, abort
import os
import time
import json
import math
import re
from collections import Counter
from openai import OpenAI

from linebot import LineBotApi, WebhookHandler
from linebot.exceptions import InvalidSignatureError
from linebot.models import MessageEvent, TextMessage, TextSendMessage
# ===== import 區域結束 =====


# ===== 多語系文字（固定字串，不交給 GPT）=====
TEXTS = {
    "zh": {
        "intro": (
            "你好，我是【微轉人資AI助手】🤖\n\n"
            "你可以直接輸入人資相關問題，例如：\n"
            "・病假規則是什麼？\n"
            "・加班費如何計算？\n"
            "・特休規定有哪些？\n"
        ),
        "fallback": "此問題在目前規章引用內容中找不到明確依據，請洽人資專員。",
        "answer_label": "【HR AI 助手回覆】\n\n",
        "disclaimer": (
            "\n\n———\n"
            "⚠️ 本回覆由微轉人資 AI 助理依據現行內部規章文件摘錄提供，僅供參考。\n"
            "如有疑慮或需正式認定，請洽人資專員並以公司公告為準。"
        ),
        "lang_rule": "請用繁體中文回覆。",
        "prefix_main": "📌 主要依據：{month} 的 {code} 版本《{name}》\n",
        "prefix_others": "📎 另參考：{others}\n\n",
    },
    "en": {
        "intro": (
            "Hi, I'm the microSHIFT HR AI assistant 🤖\n\n"
            "You can ask HR-related questions, for example:\n"
            "• Sick leave policy\n"
            "• Overtime pay calculation\n"
            "• Annual leave rules\n"
        ),
        "fallback": "I can't find a clear basis in the current internal policy excerpts. Please contact HR.",
        "answer_label": "[HR AI Assistant]\n\n",
        "disclaimer": (
            "\n\n———\n"
            "⚠️ This reply is generated by an HR AI assistant based on internal policy excerpts for reference only.\n"
            "For official confirmation, please contact HR and refer to company announcements."
        ),
        "lang_rule": "Please reply in English.",
        "prefix_main": "📌 Primary source: {month} version {code} “{name}”\n",
        "prefix_others": "📎 Additional references: {others}\n\n",
    },
    "vi": {
        "intro": (
            "Xin chào, tôi là trợ lý AI Nhân sự microSHIFT 🤖\n\n"
            "Bạn có thể hỏi các câu hỏi liên quan đến Nhân sự, ví dụ:\n"
            "• Quy định nghỉ ốm\n"
            "• Cách tính lương tăng ca\n"
            "• Quy định nghỉ phép năm\n"
        ),
        "fallback": "Tôi không tìm thấy căn cứ rõ ràng trong trích đoạn quy định hiện tại. Vui lòng liên hệ Nhân sự.",
        "answer_label": "[Trợ lý AI Nhân sự]\n\n",
        "disclaimer": (
            "\n\n———\n"
            "⚠️ Câu trả lời này do trợ lý AI Nhân sự tạo dựa trên trích đoạn quy định nội bộ và chỉ mang tính tham khảo.\n"
            "Để xác nhận chính thức, vui lòng liên hệ Nhân sự và theo thông báo của công ty."
        ),
        "lang_rule": "Vui lòng trả lời bằng tiếng Việt.",
        "prefix_main": "📌 Nguồn chính: phiên bản {month} {code} “{name}”\n",
        "prefix_others": "📎 Tham khảo thêm: {others}\n\n",
    },
}


def detect_lang(text: str) -> str:
    """
    簡易語言判斷（不額外呼叫 GPT，省錢也更穩）：
    - 有越南文變音符號 -> vi
    - 英文字母比例較高 -> en
    - 其他 -> zh
    """
    t = (text or "").strip()
    if not t:
        return "zh"

    # 越南文常見變音符號（粗略）
    if re.search(r"[àáâãăạảấầẩẫậắằẳẵặèéêẹẻẽếềểễệìíîĩịòóôõơọỏốồổỗộớờởỡợùúûũưụủứừửữựỳýỵỷỹđ]",
                 t, re.IGNORECASE):
        return "vi"

    letters = re.findall(r"[A-Za-z]", t)
    if len(letters) >= 6 and (len(letters) / max(len(t), 1)) > 0.25:
        return "en"

    return "zh"


# ===== HR Bot 設定 =====
INTRO_COOLDOWN_SECONDS = 60 * 60 * 12  # 12 小時
last_seen = {}  # 暫存每個 LINE 使用者的最後互動時間（Render 重啟會清空，正常）

SIMILARITY_THRESHOLD = 0.28  # 太常拒答可微調 0.24~0.26；太容易亂答可調高
TOP_K = 6  # 抓回的引用段落數

# ===== 追問狀態（新增）=====
FOLLOWUP_TTL_SECONDS = 60 * 30  # 30 分鐘內視為同一段對話可追問
followup_state = {}  # user_id -> {"last_q": str, "last_t": float}


def is_followup(user_text: str, lang: str, prev_q: str, prev_t: float) -> bool:
    """
    追問判定（不交給 GPT）：
    - 需有上一題，且在 TTL 內
    - 文字偏短 / 常見追問開頭 / 代名詞指涉 等
    """
    if not prev_q or not prev_t:
        return False

    now = time.time()
    if (now - prev_t) > FOLLOWUP_TTL_SECONDS:
        return False

    t = (user_text or "").strip()
    if not t:
        return False

    # 太長通常已經是新問題（可自行調整）
    if lang == "zh":
        if len(t) <= 18:
            return True
        follow_starts = ("那", "所以", "另外", "還有", "再問", "那如果", "那會", "那是不是", "會不會", "是否", "可以嗎", "怎麼算")
        refer_words = ("這個", "那個", "它", "上述", "前面", "剛剛", "上面", "剛才", "同樣", "一樣")
        if t.startswith(follow_starts) or any(w in t for w in refer_words):
            return True
        # 很短且是問句
        if len(t) <= 25 and ("嗎" in t or "?" in t or "？" in t):
            return True

    elif lang == "en":
        if len(t) <= 30:
            return True
        follow_starts = ("what about", "and", "also", "so", "then", "in that case", "does it", "do I", "will it", "is it")
        if any(t.lower().startswith(s) for s in follow_starts):
            return True

    else:  # vi
        if len(t) <= 35:
            return True
        follow_starts = ("còn", "vậy", "thế", "nếu", "và", "có", "có bị", "có được", "thì")
        if any(t.lower().startswith(s) for s in follow_starts):
            return True

    return False


# ===== 建立 Flask / OpenAI / LINE 物件 =====
app = Flask(__name__)
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
line_bot_api = LineBotApi(os.getenv("LINE_CHANNEL_ACCESS_TOKEN"))
handler = WebhookHandler(os.getenv("LINE_CHANNEL_SECRET"))

# ===== 載入 HR KB Index（啟動時讀一次）=====
KB_INDEX_PATH = os.path.join(os.path.dirname(__file__), "hr_kb_index.json")
with open(KB_INDEX_PATH, "r", encoding="utf-8") as f:
    KB = json.load(f)

KB_ITEMS = KB.get("items", [])


# ===== 向量相似度 =====
def cosine_sim(a, b):
    dot = 0.0
    na = 0.0
    nb = 0.0
    for x, y in zip(a, b):
        dot += x * y
        na += x * x
        nb += y * y
    if na == 0 or nb == 0:
        return 0.0
    return dot / (math.sqrt(na) * math.sqrt(nb))


def retrieve_chunks(query: str, top_k: int = TOP_K):
    # 1) query embedding
    q_emb = client.embeddings.create(
        model="text-embedding-3-small",
        input=query
    ).data[0].embedding

    # 2) compute similarity
    scored = []
    for it in KB_ITEMS:
        emb = it.get("embedding")
        txt = (it.get("text") or "").strip()
        if not emb or not txt:
            continue
        s = cosine_sim(q_emb, emb)
        scored.append((s, it))

    scored.sort(key=lambda x: x[0], reverse=True)
    top = scored[:top_k]

    # 3) 回傳 refs（含規章資訊）
    refs = []
    for s, it in top:
        refs.append({
            "score": float(s),
            "policy_month": it.get("policy_month", "未知月份"),
            "policy_code": it.get("policy_code", "未知版次"),
            "policy_name": it.get("policy_name", "未知辦法"),
            "source_filename": it.get("source_filename", ""),
            "chunk_id": it.get("chunk_id", 0),
            "text": (it.get("text") or "").strip(),
        })
    return refs


def collect_policies_in_order(refs):
    """
    依照 refs（相似度由高到低）收集不重複的規章清單
    回傳 [(month, code, name), ...] 第一個視為主要依據
    """
    seen = set()
    policies = []
    for r in refs:
        key = (r.get("policy_month"), r.get("policy_code"), r.get("policy_name"))
        if key in seen:
            continue
        seen.add(key)
        policies.append(key)
    return policies


def build_multi_source_prefix(T, refs):
    """
    產生多來源前綴：
    - 主要依據：refs 中最高分那批所屬規章（第一個）
    - 另參考：同一次檢索中出現的其他規章（去重）
    """
    policies = collect_policies_in_order(refs)
    if not policies:
        return "\n"

    main_month, main_code, main_name = policies[0]
    prefix = T["prefix_main"].format(month=main_month, code=main_code, name=main_name)

    if len(policies) > 1:
        others = "、".join([f"{m} {c}《{n}》" for m, c, n in policies[1:]])
        prefix += T["prefix_others"].format(others=others)
    else:
        prefix += "\n"

    return prefix


# ===== callback Webhook 接收 =====
@app.route("/callback", methods=["POST"])
def callback():
    signature = request.headers.get("X-Line-Signature")
    body = request.get_data(as_text=True)

    try:
        handler.handle(body, signature)
    except InvalidSignatureError:
        abort(400)

    return "OK"


# ===== handler：HR + RAG + GPT =====
@handler.add(MessageEvent, message=TextMessage)
def handle_message(event):
    user_text = (event.message.text or "").strip()
    user_id = event.source.user_id

    # ---- 語言判斷（固定規則）----
    lang = detect_lang(user_text)
    T = TEXTS.get(lang, TEXTS["zh"])

    # ---- intro 顯示節奏 ----
    now = time.time()
    last = last_seen.get(user_id)
    should_show_intro = (last is None) or ((now - last) > INTRO_COOLDOWN_SECONDS)
    last_seen[user_id] = now

    # ---- 追問判定（新增）----
    prev = followup_state.get(user_id, {})
    prev_q = prev.get("last_q", "")
    prev_t = prev.get("last_t", 0.0)

    follow = is_followup(user_text, lang, prev_q, prev_t)

    if follow:
        if lang == "zh":
            effective_question = f"{prev_q}\n（追問）{user_text}"
        elif lang == "en":
            effective_question = f"{prev_q}\n(Follow-up) {user_text}"
        else:
            effective_question = f"{prev_q}\n(Câu hỏi tiếp) {user_text}"
    else:
        effective_question = user_text

    # 更新追問狀態：把「有效問題」當成下一輪的上下文
    #（避免連續追問時只記得很短的一句）
    followup_state[user_id] = {"last_q": effective_question, "last_t": now}

    # ---- RAG 檢索（用 effective_question）----
    refs = retrieve_chunks(effective_question, top_k=TOP_K)
    best_score = refs[0]["score"] if refs else 0.0

    # 相似度不足：直接拒答（避免泛化到勞基法/網路常識）
    if best_score < SIMILARITY_THRESHOLD:
        core = T["fallback"]
        if should_show_intro:
            reply_text = f"{T['intro']}\n{core}{T['disclaimer']}"
        else:
            reply_text = f"{core}{T['disclaimer']}"

        line_bot_api.reply_message(
            event.reply_token,
            TextSendMessage(text=reply_text)
        )
        return

    # ---- 多來源前綴（只改這裡即可顯示多規章）----
    prefix = build_multi_source_prefix(T, refs)

    # ---- 引用內容區塊（只給必要片段）----
    context_block = "\n\n".join(
        [f"[{r['policy_code']}#{r['chunk_id']}] {r['text']}" for r in refs]
    )

    # ---- GPT Prompt（維持你原本規則，不額外加入制度角色說明）----
    prompt = f"""
[規則（非常重要）]
1) 你只能根據下方【引用內容】回答，禁止使用一般常識、網路資訊或推測補充。
2) 如果【引用內容】不足以回答，請只回覆下列句子（不要加任何補充）：
{T['fallback']}

[語言要求]
{T['lang_rule']}

[引用內容]
{context_block}

[員工問題]
{effective_question}

[回答格式要求]
- 專業、清楚、簡短
- 優先用條列
- 若有條款/條件/例外，需講清楚
""".strip()

    resp = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "你是公司內部 HR Bot（只能依據引用內容回答）"},
            {"role": "user", "content": prompt}
        ],
        temperature=0.1
    )
    gpt_answer = (resp.choices[0].message.content or "").strip()

    # ---- 組合回覆（免責聲明固定加最後，不交給 GPT）----
    if should_show_intro:
        reply_text = f"{T['intro']}\n{prefix}{T['answer_label']}{gpt_answer}{T['disclaimer']}"
    else:
        reply_text = f"{prefix}{T['answer_label']}{gpt_answer}{T['disclaimer']}"

    line_bot_api.reply_message(
        event.reply_token,
        TextSendMessage(text=reply_text)
    )


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 10000))
    app.run(host="0.0.0.0", port=port)
